name: Deploy JSONCrack to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/jsoncrack:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/jsoncrack:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to EC2 (Ubuntu)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Stop and remove existing container
          docker stop jsoncrack || true
          docker rm jsoncrack || true
          
          # Pull latest image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/jsoncrack:latest
          
          # Run new container
          docker run -d \
            --name jsoncrack \
            -p 80:8080 \
            -p 8888:8080 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/jsoncrack:latest
          
          # Clean up old images
          docker image prune -f